"""
    SOCC Constant Table
"""

N = 8
COEFF_LENGTH = 2 * N + 1

M = 300          # default
GAMMA = 1.0
ETA_THRESH = 0.85
P_MAX = 40.0
ALPHA = 0.15
NOISE_STD = 0.02
EPSILON = 1e-12

SOC_SHIFT_TRUNCATE = 0
SOC_SHIFT_WRAP = 1

SOC_YRX_FORMULA_SPEC = 0
SOC_YRX_FORMULA_FIXED = 1

SOC_OK = 0
SOC_ERR_NULL_POINTER = 1
SOC_ERR_INVALID_INDEX = 2
SOC_ERR_INVALID_MODE = 3
SOC_ERR_ENERGY_ZERO = 4
